#define DEBUG true

#define NUMBEROFULTRASENSORS 4
#define CLOSESOCKET 77

#define FRONTRIGHTSENSOR 0
#define PIN_ECHO_1 29
#define PIN_TRIGGER_1 28

#define FRONTSENSOR 1
#define PIN_ECHO_2 21
#define PIN_TRIGGER_2 22

#define FRONTLEFTSENSOR 2
#define PIN_ECHO_3 25
#define PIN_TRIGGER_3 24

#define BACKSENSOR 3
#define PIN_ECHO_4 27
#define PIN_TRIGGER_4 26

#define PIN_LIGHTSENSOR 3
#define PIN_FRONTLIGHT 6

#define PIN_LEFT 5
#define PIN_RIGHT 2
#define PIN_BACKWARD 0
#define PIN_FORWARD 1

#define PIN_BLINKER_LEFT 23
#define PIN_BLINKER_RIGHT 7

#define BLINKERMS 700

#define STRAIGHT 10
#define LEFT 11
#define RIGHT 12

#define LIGHTS_OFF 18
#define LIGHTS_ON 19
#define LIGHTS_AUTO_OFF 20
#define LIGHTS_AUTO_ON 21

#define HORN 25

#define RIDIN_DIRTY 30
#define MUSIC_OFF 31


#define MINSPEEDBACK 110
#define MAXSPEEDFORWARD 120

#define CAUTIONFRONT_CM 10
#define CAUTIONFRONTLEFT_CM 5
#define CAUTIONFRONTRIGHT_CM 5
#define CAUTIONBACK_CM 10

#define CAUTIONFACTOR_1 2
#define CAUTIONFACTOR_2 3
#define CAUTIONFACTOR_3 4
#define CAUTIONFACTOR_4 5
#define CAUTIONFACTOR_5 5


#define POSITIVERESPONSE 1
#define NEGATIVERESPONSE 0

#define REFRESHMS 200

